/**
 * Auto-generated by Parser Engine Playground
 * Parser: 5p_amenitieslist
 * Description: Generated parser configuration
 * Generated: 2026-02-05
 *
 * Usage:
 *   import { useParse5pAmenitieslist } from './useParse5pAmenitieslist'
 *   const result = await useParse5pAmenitieslist(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface FivePAmenitieslistRow {
  property_code: string | null
  yardi_code: string | null
  yardi_name: string | null
  yardi_amenity: string | null
  amount: number | null
  type: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for 5p_amenitieslist
 */
const config: ParserConfig = {
  id: '5p_amenitieslist',
  namePattern: '.*',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Amenity Code': { targetField: 'yardi_code', required: true },
    'Amenity Name': { targetField: 'yardi_name', required: true },
    'Amenity': { targetField: 'yardi_amenity', required: true },
    'Prior $': { targetField: '_skipped', transform: 'skip' },
    'Current $': { targetField: 'amount', transform: 'currency', required: true },
    'Proposed $': { targetField: '_skipped', transform: 'skip' },
    '$ Increase': { targetField: '_skipped', transform: 'skip' },
    '% Increase': { targetField: '_skipped', transform: 'skip' },
    'type': { targetField: 'type' }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.yardi_code || ''}_${row.yardi_name || ''}_${row.yardi_amenity || ''}_${row.amount || ''}`
}

/**
 * Parse a 5p amenitieslist file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParse5pAmenitieslist(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<FivePAmenitieslistRow>> {
  return useGenericParser<FivePAmenitieslistRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const fiveP_amenitieslistConfig = config
