/**
 * Auto-generated by Parser Engine Playground
 * Parser: 5p_amenitiesaudit_02_05_2026
 * Description: Generated parser configuration
 * Generated: 2026-02-06
 *
 * Usage:
 *   import { useParse5pAmenitiesaudit02052026 } from './useParse5pAmenitiesaudit02052026'
 *   const result = await useParse5pAmenitiesaudit02052026(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface FivePAmenitiesaudit02052026Row {
  property_code: string | null
  unit_name: string | null
  yardi_code: string | null
  yardi_name: string | null
  yardi_amenity: string | null
  amount: number | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for 5p_amenitiesaudit_02_05_2026
 */
const config: ParserConfig = {
  id: '5p_amenitiesaudit_02_05_2026',
  namePattern: '.*',
  headerRow: 5,
  strategy: 'standard',
  mapping: {
    'PCode': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Property': { targetField: '_skipped', transform: 'skip' },
    'Unit': { targetField: 'unit_name', required: true },
    'UTCode': { targetField: '_skipped', transform: 'skip' },
    'Unit Type': { targetField: '_skipped', transform: 'skip' },
    'UTSqFt': { targetField: '_skipped', transform: 'skip' },
    'UTRent': { targetField: '_skipped', transform: 'skip' },
    'ACode': { targetField: 'yardi_code', required: true },
    'Amenity': { targetField: 'yardi_name', required: true },
    'Amenity Name': { targetField: 'yardi_amenity', required: true },
    'AAmount': { targetField: 'amount', transform: 'currency', required: true }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_name || ''}_${row.yardi_code || ''}_${row.yardi_name || ''}_${row.yardi_amenity || ''}_${row.amount || ''}`
}

/**
 * Parse a 5p amenitiesaudit 02 05 2026 file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParse5pAmenitiesaudit02052026(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<FivePAmenitiesaudit02052026Row>> {
  return useGenericParser<FivePAmenitiesaudit02052026Row>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const fiveP_amenitiesaudit_02_05_2026Config = config
