/**
 * Auto-generated by Parser Engine Playground
 * Parser: Alerts
 * Description: Basic parser with auto-detect headers
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseAlerts } from './useParseAlerts'
 *   const result = await useParseAlerts(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface AlertsRow {
  property_code: string | null
  unit_name: string | null
  description: string | null
  resident: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for Alerts
 */
const config: ParserConfig = {
  id: 'Alerts',
  namePattern: '^5p_Alerts',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Unit': { targetField: 'unit_name', required: true },
    'Description': { targetField: 'description', required: true },
    'Resident': { targetField: 'resident', required: true }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_name || ''}_${row.description || ''}_${row.resident || ''}`
}

/**
 * Parse a Alerts file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseAlerts(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<AlertsRow>> {
  return useGenericParser<AlertsRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const AlertsConfig = config
