/**
 * Auto-generated by Parser Engine Playground (Refined by Engine Output)
 * Parser: amenities_audit
 * Description: Parser for 5p_amenitiesaudit report from Yardi.
 * Generated: 2026-02-05
 *
 * Usage:
 *   import { useParseAmenitiesAudit } from './useParseAmenitiesAudit'
 *   const result = await useParseAmenitiesAudit(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 */
export interface AmenitiesAuditRow {
  property_code: string | null
  unit_name: string | null
  yardi_code: string | null
  yardi_name: string | null
  yardi_amenity: string | null
  amount: number | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for amenities_audit
 */
const config: ParserConfig = {
  id: 'amenities_audit',
  namePattern: '.*',
  headerRow: 5,
  strategy: 'standard',
  mapping: {
    'PCode': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Unit': { targetField: 'unit_name', required: true },
    'ACode': { targetField: 'yardi_code', required: true },
    'Amenity': { targetField: 'yardi_name', required: true },
    'Amenity Name': { targetField: 'yardi_amenity', required: true },
    'AAmount': { targetField: 'amount', transform: 'currency', required: true }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_name || ''}_${row.yardi_code || ''}_${row.yardi_name || ''}_${row.yardi_amenity || ''}_${row.amount || ''}`
}

/**
 * Parse a amenities_audit file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseAmenitiesAudit(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<AmenitiesAuditRow>> {
  return useGenericParser<AmenitiesAuditRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const amenitiesAuditConfig = config
