/**
 * Auto-generated by Parser Engine Playground
 * Parser: Availables
 * Description: Basic parser with auto-detect headers
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseAvailables } from './useParseAvailables'
 *   const result = await useParseAvailables(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface AvailablesRow {
  property_code: string | null
  unit_name: string | null
  floor_plan: string | null
  bedroom_count: number | null
  offered_rent: number | null
  available_date: string | null
  days_vacant: number | null
  sqft: number | null
  status: string | null
  amenities: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for Availables
 */
const config: ParserConfig = {
  id: 'Availables',
  namePattern: '^5p_Availables',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Unit': { targetField: 'unit_name', required: true },
    'Unit Type': { targetField: 'floor_plan', required: true },
    'BR': { targetField: 'bedroom_count', transform: 'number', required: true },
    'Market Rent': { targetField: 'offered_rent', transform: 'currency', required: true },
    'Date Available': { targetField: 'available_date', transform: 'date', required: true },
    'Days Vac.': { targetField: 'days_vacant', transform: 'number', required: true },
    'Sqft': { targetField: 'sqft', transform: 'number', required: true },
    'Occ.': { targetField: 'status', required: true },
    'Amenities': { targetField: 'amenities', required: true },
    'Brochure': { targetField: '_skipped', transform: 'skip' },
    'Specials': { targetField: '_skipped', transform: 'skip' },
    'Hold Until': { targetField: '_skipped', transform: 'skip' }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_name || ''}_${row.floor_plan || ''}_${row.bedroom_count || ''}_${row.offered_rent || ''}_${row.available_date || ''}_${row.days_vacant || ''}_${row.sqft || ''}_${row.status || ''}_${row.amenities || ''}`
}

/**
 * Parse a Availables file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseAvailables(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<AvailablesRow>> {
  return useGenericParser<AvailablesRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const AvailablesConfig = config
