/**
 * Auto-generated by Parser Engine Playground (Refined by Engine Output)
 * Parser: amenities_list
 * Description: Parser for 5p_amenitieslist report from Yardi.
 * Generated: 2026-02-05
 *
 * Usage:
 *   import { useParseAmenitiesList } from './useParseAmenitiesList'
 *   const result = await useParseAmenitiesList(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 */
export interface AmenitiesListRow {
  property_code: string | null
  yardi_code: string | null
  yardi_name: string | null
  yardi_amenity: string | null
  amount: number | null
  type: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for amenities_list
 */
const config: ParserConfig = {
  id: 'amenities_list',
  namePattern: '.*', // Matches any file name for now as per engine output
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Amenity Code': { targetField: 'yardi_code', required: true },
    'Amenity Name': { targetField: 'yardi_name', required: true },
    'Amenity': { targetField: 'yardi_amenity', required: true },
    'Current $': { targetField: 'amount', transform: 'currency', required: true },
    'type': { targetField: 'type' }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.yardi_code || ''}_${row.yardi_name || ''}_${row.yardi_amenity || ''}_${row.amount || ''}`
}

/**
 * Parse a amenities_list file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseAmenitiesList(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<AmenitiesListRow>> {
  return useGenericParser<AmenitiesListRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const amenitiesListConfig = config
