/**
 * Auto-generated by Parser Engine Playground
 * Parser: Applications
 * Description: Basic parser with auto-detect headers
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseApplications } from './useParseApplications'
 *   const result = await useParseApplications(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface ApplicationsRow {
  leasing_agent: string | null
  applicant: string | null
  application_date: string | null
  property_code: string | null
  unit_name: string | null
  screening_result: string | null
  screening_last_updated: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for Applications
 */
const config: ParserConfig = {
  id: 'Applications',
  namePattern: '^5p_Applications',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'Agent': { targetField: 'leasing_agent', required: true },
    'Guest': { targetField: 'applicant', required: true },
    'Application Date': { targetField: 'application_date', transform: 'date', required: true },
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Unit': { targetField: 'unit_name', required: true },
    'Screening Result': { targetField: 'screening_result', required: false },  // Optional - pending apps won't have this
    'Screening Last Updated': { targetField: 'screening_last_updated', transform: 'date', required: false }  // Optional
  },
  getUniqueId: (row) => `${row.leasing_agent || ''}_${row.applicant || ''}_${row.application_date || ''}_${row.property_code || ''}_${row.unit_name || ''}_${row.screening_result || ''}_${row.screening_last_updated || ''}`
}

/**
 * Parse a Applications file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseApplications(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<ApplicationsRow>> {
  return useGenericParser<ApplicationsRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const ApplicationsConfig = config
