/**
 * Auto-generated by Parser Engine Playground
 * Parser: Notices
 * Description: Basic parser with auto-detect headers
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseNotices } from './useParseNotices'
 *   const result = await useParseNotices(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface NoticesRow {
  move_out_date: string | null
  property_code: string | null
  unit_name: string | null
  resident: string | null
  status: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for Notices
 */
const config: ParserConfig = {
  id: 'Notices',
  namePattern: '^5p_Notices',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'Move Out Date': { targetField: 'move_out_date', transform: 'date', required: true },
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Unit': { targetField: 'unit_name', required: true },
    'Resident': { targetField: 'resident', required: true },
    'Status': { targetField: 'status', required: true }
  },
  getUniqueId: (row) => `${row.move_out_date || ''}_${row.property_code || ''}_${row.unit_name || ''}_${row.resident || ''}_${row.status || ''}`
}

/**
 * Parse a Notices file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseNotices(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<NoticesRow>> {
  return useGenericParser<NoticesRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const NoticesConfig = config
