/**
 * Auto-generated by Parser Engine Playground
 * Parser: Transfers
 * Description: Generated parser configuration
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseTransfers } from './useParseTransfers'
 *   const result = await useParseTransfers(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface TransfersRow {
  from_property_code: string | null
  from_status: string | null
  from_unit_name: string | null
  resident: string | null
  to_unit_name: string | null
  to_property_code: string | null
  to_status: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for Transfers
 */
const config: ParserConfig = {
  id: 'Transfers',
  namePattern: '^5p_Transfers',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'From Property': { targetField: 'from_property_code', transform: 'yardi_code', required: true },
    'From Resident': { targetField: 'from_status', required: true },
    'From Unit': { targetField: 'from_unit_name', required: true },
    'Resident Name': { targetField: 'resident', required: true },
    'To Unit': { targetField: 'to_unit_name', required: true },
    'To Property': { targetField: 'to_property_code', transform: 'yardi_code', required: true },
    'New Resident': { targetField: 'to_status' }
  },
  getUniqueId: (row) => `${row.from_property_code || ''}_${row.from_status || ''}_${row.from_unit_name || ''}_${row.resident || ''}_${row.to_unit_name || ''}_${row.to_property_code || ''}`
}

/**
 * Parse a Transfers file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseTransfers(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<TransfersRow>> {
  return useGenericParser<TransfersRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const TransfersConfig = config
