/**
 * Auto-generated by Parser Engine Playground (Placeholder Impl)
 * Parser: units
 * Description: Placeholder parser for Unit lists
 * Generated: 2026-01-24
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

export interface UnitRow {
  property_code: string | null
  unit_code: string | null
  status: string | null
  beds: string | null
  baths: string | null
  sqft: string | null
  market_rent: number | null
  unit_id?: string | null
  unique_id?: string
}

const config: ParserConfig = {
  id: 'units',
  namePattern: '^5p_units', // Adjust pattern as needed
  headerRow: 1,
  strategy: 'standard', // Assumes flat extraction
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code' },
    'Unit': { targetField: 'unit_code', required: true },
    'Status': { targetField: 'status' },
    'Bedrooms': { targetField: 'beds' },
    'Bathrooms': { targetField: 'baths' },
    'Sq Ft': { targetField: 'sqft', transform: 'trim' },
    'Market Rent': { targetField: 'market_rent', transform: 'currency' }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_code || ''}`
}

export async function useParseUnits(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<UnitRow>> {
  return useGenericParser<UnitRow>(file, config, options)
}

export const unitsConfig = config
