/**
 * Auto-generated by Parser Engine Playground
 * Parser: LeasedUnits
 * Description: Generated parser configuration
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseLeasedunits } from './useParseLeasedunits'
 *   const result = await useParseLeasedunits(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface LeasedunitsRow {
  property_code: string | null
  unit_name: string | null
  floor_plan: string | null
  unit_status: string | null
  resident: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for LeasedUnits
 */
const config: ParserConfig = {
  id: 'LeasedUnits',
  namePattern: '^5p_Leased_Units',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Unit': { targetField: 'unit_name', required: true },
    'Unit Type': { targetField: 'floor_plan', required: true },
    'Unit Status': { targetField: 'unit_status', required: true },
    'Resident': { targetField: 'resident', required: true }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_name || ''}_${row.floor_plan || ''}_${row.unit_status || ''}_${row.resident || ''}`
}

/**
 * Parse a LeasedUnits file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseLeasedunits(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<LeasedunitsRow>> {
  return useGenericParser<LeasedunitsRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const LeasedUnitsConfig = config
