/**
 * Auto-generated by Parser Engine Playground (Placeholder Impl)
 * Parser: residents
 * Description: Placeholder parser for Resident rosters
 * Generated: 2026-01-24
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

export interface ResidentRow {
  property_code: string | null
  unit_code: string | null
  resident_name: string | null
  status: string | null
  lease_start: string | null
  lease_end: string | null
  rent: number | null
  balance: number | null
  unit_id?: string | null
  unique_id?: string
}

const config: ParserConfig = {
  id: 'residents',
  namePattern: '^5p_residents', // Adjust pattern as needed
  headerRow: 1, // Often with yardi_report the headers are deeper, but placeholder sets 1 for now or adjusts
  // NOTE: Yardi reports often have headers at row 4 or 6. We will assume standard for now but strategy is yardi_report
  strategy: 'yardi_report',
  mapping: {
    'Unit': { targetField: 'unit_code', required: true },
    'Name': { targetField: 'resident_name' },
    'Status': { targetField: 'status' },
    'Lease From': { targetField: 'lease_start', transform: 'date' },
    'Lease To': { targetField: 'lease_end', transform: 'date' },
    'Rent': { targetField: 'rent', transform: 'currency' },
    'Balance': { targetField: 'balance', transform: 'currency' }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_code || ''}_${row.resident_name || ''}`
}

export async function useParseResidents(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<ResidentRow>> {
  return useGenericParser<ResidentRow>(file, config, options)
}

export const residentsConfig = config
