/**
 * Auto-generated by Parser Engine Playground
 * Parser: Delinquencies
 * Description: Basic parser with auto-detect headers
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseDelinquencies } from './useParseDelinquencies'
 *   const result = await useParseDelinquencies(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface DelinquenciesRow {
  property_code: string | null
  unit_name: string | null
  tenancy_id: string | null
  resident: string | null
  total_unpaid: number | null
  days_0_30: number | null
  days_31_60: number | null
  days_61_90: number | null
  days_90_plus: number | null
  prepays: number | null
  balance: number | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for Delinquencies
 */
const config: ParserConfig = {
  id: 'Delinquencies',
  namePattern: '^5p_Delinquencies',
  headerRow: 3,
  strategy: 'standard',
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Unit': { targetField: 'unit_name', required: true },
    'Resident': { targetField: 'tenancy_id', required: true },
    'Name': { targetField: 'resident', required: true },
    'Total': { targetField: 'total_unpaid', transform: 'currency', required: true },
    '0-30': { targetField: 'days_0_30', transform: 'currency', required: true },
    '31-60': { targetField: 'days_31_60', transform: 'currency', required: true },
    '61-90': { targetField: 'days_61_90', transform: 'currency', required: true },
    'Over 90': { targetField: 'days_90_plus', transform: 'currency', required: true },
    'Prepays': { targetField: 'prepays', transform: 'currency', required: true },
    'Balance': { targetField: 'balance', transform: 'currency', required: true }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_name || ''}_${row.tenancy_id || ''}_${row.resident || ''}_${row.total_unpaid || ''}_${row.days_0_30 || ''}_${row.days_31_60 || ''}_${row.days_61_90 || ''}_${row.days_90_plus || ''}_${row.prepays || ''}_${row.balance || ''}`
}

/**
 * Parse a Delinquencies file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseDelinquencies(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<DelinquenciesRow>> {
  return useGenericParser<DelinquenciesRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const DelinquenciesConfig = config
