/**
 * Auto-generated by Parser Engine Playground
 * Parser: ExpiringLeases
 * Description: Expiring Leases report (yardi_report strategy). Property groups extracted from "(code)" pattern. Rows without valid unit_code are filtered.
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseExpiringleases } from './useParseExpiringleases'
 *   const result = await useParseExpiringleases(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface ExpiringleasesRow {
  unit_name: string | null
  floor_plan: string | null
  status: string | null
  market_rent: number | null
  sqft: string | null
  deposit: string | null
  tenancy_code: string | null
  resident: string | null
  lease_rent: number | null
  lease_start_date: string | null
  lease_end_date: string | null
  move_out_date: string | null
  phone: string | null

  property_code: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for ExpiringLeases
 */
const config: ParserConfig = {
  id: 'ExpiringLeases',
  namePattern: '^5p_ExpiringLeases',
  headerRow: 4,
  strategy: 'yardi_report',
  mapping: {
    'Unit': { targetField: 'unit_name', required: true },
    'Unit Type': { targetField: 'floor_plan' },
    'Resident Status': { targetField: 'status', required: true },
    'Market Rent': { targetField: 'market_rent', transform: 'currency' },
    'Unit SqFt': { targetField: 'sqft' },
    'Sec Dep On Hand': { targetField: 'deposit', transform: 'currency' },
    'Resident Code': { targetField: 'tenancy_code', required: true },
    'Resident Name': { targetField: 'resident', required: true },
    'Actual Rent': { targetField: 'lease_rent', transform: 'currency' },
    'Lease From': { targetField: 'lease_start_date', transform: 'date', required: true },
    'Lease To': { targetField: 'lease_end_date', transform: 'date', required: true },
    'Move Out': { targetField: 'move_out_date', transform: 'date' },
    'Tel Num(Office)': { targetField: 'phone', transform: 'phone', mergeGroup: 'phone', mergePriority: 2 },
    'Tel Num(Home)': { targetField: 'phone', transform: 'phone', mergeGroup: 'phone', mergePriority: 1 }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_name || ''}_${row.status || ''}_${row.tenancy_code || ''}_${row.resident || ''}_${row.lease_start_date || ''}_${row.lease_end_date || ''}`
}

/**
 * Parse a ExpiringLeases file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseExpiringleases(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<ExpiringleasesRow>> {
  return useGenericParser<ExpiringleasesRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const ExpiringLeasesConfig = config
