/**
 * Auto-generated by Parser Engine Playground
 * Parser: WorkOrders
 * Description: Basic parser with auto-detect headers
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseWorkorders } from './useParseWorkorders'
 *   const result = await useParseWorkorders(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface WorkordersRow {
  yardi_work_order_id: string | null
  description: string | null
  call_date: string | null
  property_code: string | null
  unit_name: string | null
  resident: string | null
  phone: string | null
  category: string | null
  status: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for WorkOrders
 */
const config: ParserConfig = {
  id: 'WorkOrders',
  namePattern: '^5p_WorkOrders',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'WO#': { targetField: 'yardi_work_order_id', required: true },
    'Brief Description': { targetField: 'description', required: true },
    'Call Date': { targetField: 'call_date', transform: 'date', required: true },
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Unit': { targetField: 'unit_name' },
    'Resident': { targetField: 'resident' },
    'Phone #': { targetField: 'phone', transform: 'phone' },
    'Category': { targetField: 'category' },
    'Status': { targetField: 'status', required: true }
  },
  getUniqueId: (row) => `${row.yardi_work_order_id || ''}_${row.description || ''}_${row.call_date || ''}_${row.property_code || ''}_${row.status || ''}`
}

/**
 * Parse a WorkOrders file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseWorkorders(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<WorkordersRow>> {
  return useGenericParser<WorkordersRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const WorkOrdersConfig = config
