/**
 * Auto-generated by Parser Engine Playground
 * Parser: residents_status
 * Description: Residents Status report with fill-down for property grouping
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseResidentsStatus } from './useParseResidentsStatus'
 *   const result = await useParseResidentsStatus(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface ResidentsStatusRow {
  property_code: string | null
  unit_name: string | null
  tenancy_id: string | null
  type: string | null
  resident: string | null
  rent: string | null
  deposit: string | null
  status: string | null
  lease_start_date: string | null
  lease_end_date: string | null
  move_in_date: string | null
  move_out_date: string | null
  phone: string | null
  phone: string | null
  phone: string | null
  email: string | null
  unit_address: string | null
  unit_city_state_zip: string | null
  tenant_address: string | null
  tenant_city_state_zip: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for residents_status
 */
const config: ParserConfig = {
  id: 'residents_status',
  namePattern: '^5p_residents_status',
  headerRow: 6,
  strategy: 'fill_down',
  fillDownFields: ['property_code'],
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true, fillDown: true },
    'Unit': { targetField: 'unit_name', required: true },
    'Code': { targetField: 'tenancy_id', required: true },
    'Type': { targetField: 'type' },
    'Tenant': { targetField: 'resident' },
    'Rent': { targetField: 'rent' },
    'Deposit': { targetField: 'deposit' },
    'Status': { targetField: 'status', required: true },
    'From': { targetField: 'lease_start_date', transform: 'date' },
    'To': { targetField: 'lease_end_date', transform: 'date' },
    'In': { targetField: 'move_in_date', transform: 'date' },
    'Out': { targetField: 'move_out_date', transform: 'date' },
    'Tel# (O)': { targetField: 'phone', transform: 'phone', mergeGroup: 'phone', mergePriority: 3 },
    'Tel# (H)': { targetField: 'phone', transform: 'phone', mergeGroup: 'phone', mergePriority: 2 },
    'Tel# (M)': { targetField: 'phone', transform: 'phone', mergeGroup: 'phone', mergePriority: 1 },
    'Email': { targetField: 'email' },
    'Unit Address': { targetField: 'unit_address' },
    'Unit City/State/Zip': { targetField: 'unit_city_state_zip' },
    'Tenant Address': { targetField: 'tenant_address' },
    'Tenant City/State/Zip': { targetField: 'tenant_city_state_zip' }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_name || ''}_${row.tenancy_id || ''}_${row.status || ''}`
}

/**
 * Parse a residents status file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseResidentsStatus(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<ResidentsStatusRow>> {
  return useGenericParser<ResidentsStatusRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const residents_statusConfig = config
