/**
 * Auto-generated by Parser Engine Playground
 * Parser: MakeReady
 * Description: Basic parser with auto-detect headers
 * Generated: 2026-01-25
 *
 * Usage:
 *   import { useParseMakeready } from './useParseMakeready'
 *   const result = await useParseMakeready(file, { unitsLookup })
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

/**
 * Type definition for parsed rows from this parser.
 * Customize this interface based on your data structure.
 */
export interface MakereadyRow {
  property_code: string | null
  bedrooms: string | null
  rent: string | null
  sqft: string | null
  make_ready_date: string | null
  unit_name: string | null
  status: string | null
  unit_id?: string | null
  unique_id?: string
}

/**
 * Parser configuration for MakeReady
 */
const config: ParserConfig = {
  id: 'MakeReady',
  namePattern: '^5p_MakeReady',
  headerRow: 1,
  strategy: 'standard',
  mapping: {
    'Property': { targetField: 'property_code', transform: 'yardi_code', required: true },
    'Bedrooms': { targetField: 'bedrooms', required: true },
    'Rent': { targetField: 'rent', required: true },
    'SqFt': { targetField: 'sqft', required: true },
    'Date Ready': { targetField: 'make_ready_date', transform: 'date', required: true },
    'Unit': { targetField: 'unit_name', required: true },
    'Occupancy': { targetField: 'status', required: true }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.bedrooms || ''}_${row.rent || ''}_${row.sqft || ''}_${row.make_ready_date || ''}_${row.unit_name || ''}_${row.status || ''}`
}

/**
 * Parse a MakeReady file.
 *
 * @param file - The Excel/CSV file to parse
 * @param options - Optional: { unitsLookup } for unit ID resolution
 * @returns ParsedResult with data array and metadata
 */
export async function useParseMakeready(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<MakereadyRow>> {
  return useGenericParser<MakereadyRow>(file, config, options)
}

/**
 * Export the config for external use or modification
 */
export const MakeReadyConfig = config
