/**
 * Auto-generated by Parser Engine Playground (Generic Impl)
 * Parser: yardi_report_generic
 * Description: Generic entry point for arbitrary Yardi reports
 * Generated: 2026-01-24
 */

import { useGenericParser } from '../useGenericParser'
import type { ParserConfig, ParsedResult } from '../../types'

export interface YardiReportRow {
  property_code: string | null
  unit_code: string | null
  tenant_code: string | null
  name: string | null
  [key: string]: any // Flexible for generic report
}

const config: ParserConfig = {
  id: 'yardi_report_generic',
  namePattern: '.*', // Matches anything if chosen manually
  headerRow: 4, // Default guess for Yardi reports
  strategy: 'yardi_report',
  mapping: {
    'Unit': { targetField: 'unit_code' },
    'Code': { targetField: 'tenant_code' },
    'Name': { targetField: 'name' }
  },
  getUniqueId: (row) => `${row.property_code || ''}_${row.unit_code || ''}_${row.tenant_code || ''}`
}

export async function useParseYardiReport(
  file: File,
  options?: {
    unitsLookup?: Array<{ apt_code: string; name: string; unit_id: string }>
  }
): Promise<ParsedResult<YardiReportRow>> {
  return useGenericParser<YardiReportRow>(file, config, options)
}

export const yardiReportConfig = config
