-- This migration is now consolidated into 20260216000001_rebuild_leasing_pipeline_with_pricing.sql
-- All views were dropped with CASCADE and must be restored in 000001 to maintain dependency order.
-- EMPTY MIGRATION
