import nodemailer from 'nodemailer'
import { serverSupabaseServiceRole } from '#supabase/server'
import { Database } from '../../../../../types/supabase'

export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  const { runId } = body

  if (!runId) {
    throw createError({
      statusCode: 400,
      statusMessage: 'Missing runId'
    })
  }

  const config = useRuntimeConfig()
  const client = serverSupabaseServiceRole<Database>(event)

  console.log('[Email API] Using host:', config.public.mailersendServer, 'port:', config.public.mailersendPort)
  
  try {
    // 1. Fetch the Solver Run data
    const { data: run, error: runError } = await client
      .from('solver_runs')
      .select('*')
      .eq('id', runId)
      .single()

    if (runError || !run) throw runError || new Error('Run not found')

    const propertiesProcessed = run.properties_processed || []
    if (propertiesProcessed.length === 0) {
      return { success: true, message: 'No properties to notify' }
    }

    // 2. Fetch all active recipients for these properties
    const { data: recipients, error: recError } = await client
      .from('property_notification_recipients')
      .select('email, property_code')
      .in('property_code', propertiesProcessed)
      .eq('is_active', true)

    if (recError) throw recError
    if (!recipients || recipients.length === 0) {
      return { success: true, message: 'No recipients found for these properties' }
    }

    // 3. Consolidate by Email
    const emailToProperties = recipients.reduce((acc, curr) => {
      if (!acc[curr.email]) acc[curr.email] = []
      acc[curr.email].push(curr.property_code)
      return acc
    }, {} as Record<string, string[]>)

    // 4. Setup Transporter
    const transporter = nodemailer.createTransport({
      host: config.public.mailersendServer,
      port: parseInt(config.public.mailersendPort as string),
      auth: {
        user: config.public.mailersendUsername,
        pass: config.mailersendPassword
      }
    })

    const summaryData = run.summary as any
    const results = []

    // 5. Send consolidated emails
    for (const [email, propertyCodes] of Object.entries(emailToProperties)) {
      let htmlContent = `
        <div style="font-family: sans-serif; max-width: 600px; margin: auto; color: #333;">
          <h2 style="color: #4f46e5; border-bottom: 2px solid #4f46e5; padding-bottom: 10px;">Daily Solver Summary</h2>
          <p><strong>Batch ID:</strong> ${run.batch_id}</p>
          <p><strong>Date:</strong> ${new Date(run.upload_date).toLocaleString()}</p>
          <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
      `

      for (const code of propertyCodes) {
        const s = summaryData[code]
        if (!s) continue

        htmlContent += `
          <div style="margin-bottom: 30px; padding: 15px; background: #f9fafb; border-radius: 8px;">
            <h3 style="margin-top: 0; color: #111;">Property: ${code}</h3>
            <table style="width: 100%; border-collapse: collapse;">
              <tr><td style="padding: 4px 0;">New Tenancies:</td><td style="text-align: right; font-weight: bold;">${s.tenanciesNew}</td></tr>
              <tr><td style="padding: 4px 0;">New Residents:</td><td style="text-align: right; font-weight: bold;">${s.residentsNew}</td></tr>
              <tr><td style="padding: 4px 0;">Lease Renewals:</td><td style="text-align: right; font-weight: bold;">${s.leasesRenewed}</td></tr>
              <tr><td style="padding: 4px 0;">Notices Processed:</td><td style="text-align: right; font-weight: bold;">${s.noticesProcessed}</td></tr>
              <tr><td style="padding: 4px 0;">Applications Saved:</td><td style="text-align: right; font-weight: bold;">${s.applicationsSaved}</td></tr>
            </table>
          </div>
        `
      }

      htmlContent += `
          <p style="font-size: 12px; color: #666; text-align: center; margin-top: 40px;">
            This is an automated report generated by the EE Manager Solver System.
          </p>
        </div>
      `

      try {
        await transporter.sendMail({
          from: `"${config.public.mailersendSmtpName || 'EE Manager'}" <${config.public.mailersendUsername || 'noreply@ee-manager.com'}>`,
          to: email,
          subject: `Daily Solver Summary - ${new Date().toLocaleDateString()}`,
          html: htmlContent
        })
        results.push({ email, status: 'sent' })
      } catch (sendError: any) {
        console.error(`[Email] Failed to send to ${email}:`, sendError)
        results.push({ email, status: 'failed', error: sendError.message })
      }
    }

    return {
      success: true,
      results
    }
  } catch (error: any) {
    console.error('[Email API] Global error:', error)
    throw createError({
      statusCode: 500,
      statusMessage: error.message || 'Internal Server Error'
    })
  }
})
