import nodemailer from 'nodemailer'
import { serverSupabaseServiceRole } from '#supabase/server'
import { Database } from '../../../../../types/supabase'

function generateAuditHtml(content: string, date: string, batchId: string): string {
  // Light markdown → HTML conversion for audit report email
  const lines = content.split('\n')
  const htmlLines = lines.map(line => {
    // Headers
    if (line.startsWith('### ')) return `<h3>${line.slice(4)}</h3>`
    if (line.startsWith('## ')) return `<h2>${line.slice(3)}</h2>`
    if (line.startsWith('# ')) return `<h1>${line.slice(2)}</h1>`
    // Horizontal rule
    if (line.trim() === '---') return '<hr>'
    // Table rows — render as preformatted to preserve alignment
    if (line.trim().startsWith('|')) return `<code style="display:block;font-size:12px;white-space:pre">${line}</code>`
    // Blank lines
    if (line.trim() === '') return '<br>'
    // Inline bold
    const withBold = line.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    // Code backtick
    const withCode = withBold.replace(/`(.+?)`/g, '<code>$1</code>')
    return `<p style="margin:2px 0">${withCode}</p>`
  })

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a2e; background: #f8f9fa; margin: 0; padding: 20px; }
  .container { max-width: 860px; margin: 0 auto; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.08); }
  .header { background: #1a1a2e; color: #ffffff; padding: 24px 32px; }
  .header h1 { margin: 0; font-size: 20px; font-weight: 600; }
  .header p { margin: 4px 0 0; font-size: 13px; color: #94a3b8; }
  .body { padding: 24px 32px; }
  h1 { font-size: 20px; color: #1a1a2e; margin: 20px 0 8px; }
  h2 { font-size: 16px; color: #1e40af; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin: 20px 0 8px; }
  h3 { font-size: 14px; color: #374151; margin: 14px 0 4px; }
  hr { border: none; border-top: 1px solid #e2e8f0; margin: 16px 0; }
  p { font-size: 13px; line-height: 1.6; color: #374151; }
  code { font-family: 'SFMono-Regular', Consolas, monospace; font-size: 12px; background: #f1f5f9; padding: 1px 4px; border-radius: 3px; color: #0f172a; }
  strong { color: #111827; }
  .footer { padding: 16px 32px; background: #f8f9fa; border-top: 1px solid #e2e8f0; font-size: 11px; color: #9ca3af; }
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>Daily Solver Audit — ${date}</h1>
    <p>Batch: ${batchId} &nbsp;|&nbsp; Tier 2 Data Architect Report</p>
  </div>
  <div class="body">
    ${htmlLines.join('\n')}
  </div>
  <div class="footer">
    Generated by EE Manager &nbsp;|&nbsp; Automated Audit System
  </div>
</div>
</body>
</html>`
}

export default defineEventHandler(async (event) => {
  const body = await readBody(event)
  const { content, date, batchId } = body

  if (!content || !date) {
    throw createError({ statusCode: 400, statusMessage: 'Missing content or date' })
  }

  const config = useRuntimeConfig()
  const client = serverSupabaseServiceRole<Database>(event)

  try {
    // Fetch all active audit recipients, deduplicated by email
    const { data: recipients, error: recError } = await client
      .from('property_notification_recipients')
      .select('email')
      .eq('is_active', true)
      .contains('notification_types', ['audit'])

    if (recError) throw recError
    if (!recipients || recipients.length === 0) {
      return { success: true, message: 'No audit recipients configured' }
    }

    // Deduplicate emails (a user may have 'audit' on multiple property rows)
    const uniqueEmails = [...new Set(recipients.map(r => r.email))]

    const transporter = nodemailer.createTransport({
      host: config.public.mailersendServer,
      port: parseInt(config.public.mailersendPort as string),
      auth: {
        user: config.public.mailersendUsername,
        pass: config.mailersendPassword
      }
    })

    const htmlContent = generateAuditHtml(content, date, batchId || 'N/A')
    const results = []

    for (const email of uniqueEmails) {
      try {
        await transporter.sendMail({
          from: `"${config.public.mailersendSmtpName || 'EE Manager'}" <${config.public.mailersendUsername}>`,
          to: email,
          subject: `Daily Audit Report — ${date}`,
          html: htmlContent
        })
        results.push({ email, status: 'sent' })
      } catch (sendError: any) {
        console.error(`[Audit Email] Failed to send to ${email}:`, sendError)
        results.push({ email, status: 'failed', error: sendError.message })
      }
    }

    return { success: true, results }
  } catch (error: any) {
    console.error('[Audit Email API] Error:', error)
    throw createError({ statusCode: 500, statusMessage: error.message || 'Internal Server Error' })
  }
})
